### ISSUE TITLE
Testing for invalid characters in log_type

### ISSUE THREAD

**Issue by slagelwa** [yokawasa/azure-log-analytics-data-collector#11]
According to the DataCollector API [documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/data-collector-api) for the log type can only contain letters, numbers, and the underscore character, and may not exceed 100 characters.  However the client.py code is testing for `isalpha()` which only checks for alphabet characters which excludes underscores.  Could you change the test to include '_' and test the length?

**Comment by yokawasa** [comment]
@slagelwa thanks for the inssue. I'll work for it.

**Comment by yokawasa** [comment]
I published azure-loganalytics-datacollector-api-0.3.0 (ruby version) where I added the following validation check. I'll work on python version pretty soon
```ruby
        def is_valid_log_type(s)
          return ( s.match(/^[a-zA-Z0-9_]+$/) && s.length <= 100 ) ? true : false
        end
```  
- https://rubygems.org/gems/azure-loganalytics-datacollector-api

**Comment by slagelwa** [comment]
Thanks!!
________________________________

**Comment by yokawasa** [comment]
@slagelwa I published python client 0.3.0 ( azure-log-analytics-data-collector) too

- https://pypi.org/project/azure-log-analytics-data-collector-api/
- code diff:  https://github.com/yokawasa/azure-log-analytics-data-collector-python/commit/38961029c20dfb3a48385a559a4f664e19e5feef

**Comment by slagelwa** [comment]
FYI works great.  Thanks!

**Comment by yokawasa** [comment]
@slagelwa  Thanks for the confirmation!
