### ISSUE TITLE
Exception: string argument without an encoding

### ISSUE THREAD

**Issue by yokawasa** [yokawasa/azure-log-analytics-data-collector#2]
Exception reported from @jahidakhtargit

I'm getting below exception while creating the signature. 
`string argument without an encoding`

**Comment by yokawasa** [comment]
@jahidakhtargit  Could you please provide the following info:
- Which library did you use?: Ruby, Python, or PHP library?
- Information of your environment on which you use the library (ie, language version, OS & it version etc )

**Comment by jahidakhtargit** [comment]
I am using python 3. In the below code I am getting exception:
utf8_signs = None
    try:
        utf8_signs = bytes(signs).encode("utf-8")
        print("utf8_signs = {}".format(utf8_signs))
    except Exception as e:
        print("Exception occurred: {}".format(str(e)))

**Comment by yokawasa** [comment]
Thanks! I was able to reproduce the same exception . I'll fix this and get back to you short

**Comment by yokawasa** [comment]
@jahidakhtargit  please install new package [azure-log-analytics-data-collector-api 0.2.0](https://pypi.org/project/azure-log-analytics-data-collector-api/)
```
pip install azure-log-analytics-data-collector-api --upgrade
```

**Comment by jahidakhtargit** [comment]
@yokawasa, thanks for the info. Will upgrade and let you know.

**Comment by jahidakhtargit** [comment]
@yokawasa not working, same exception I'm getting

**Comment by jahidakhtargit** [comment]
@yokawasa Exception in the below code, nothing to do with azure here it seems.

signs = "POST\n{}\napplication/json\nx-ms-date:{}\n/api/logs".format(str(content_length), date)
    utf8_signs = None
    try:
        utf8_signs = bytes(signs).encode("utf-8")
        print("utf8_signs = {}".format(utf8_signs))
    except Exception as e:
        print("Exception occurred: {}".format(str(e)))

**Comment by yokawasa** [comment]
@jahidakhtargit Please make sure if you have installed the latest package - azure-log-analytics-data-collector-api-0.2.0
```
$ pip install azure-log-analytics-data-collector-api --upgrade
$ pip list |grep azure-log-analytics-data-collector-api
azure-log-analytics-data-collector-api 0.2.0
```
Or if you're directly using source code in Github, please git clone the latest code:  
- https://github.com/yokawasa/azure-log-analytics-data-collector/blob/master/python/datacollectorapi/client.py

As you can see, the latest __signature function in [client.py](https://github.com/yokawasa/azure-log-analytics-data-collector/blob/master/python/datacollectorapi/client.py) is like this:  
```python
    def __signature(self, date, content_length):
        sigs= "POST\n{}\napplication/json\nx-ms-date:{}\n/api/logs".format(
                            str(content_length),date)
        utf8_sigs = sigs.encode('utf-8')
        decoded_shared_key = base64.b64decode(self.shared_key)
        hmac_sha256_sigs = hmac.new(
                decoded_shared_key, utf8_sigs,digestmod=hashlib.sha256).digest()
        encoded_hash = base64.b64encode(hmac_sha256_sigs).decode('utf-8')
        authorization = "SharedKey {}:{}".format(self.customer_id,encoded_hash)
        return authorization
```
Please try with the latest package or source code

**Comment by jahidakhtargit** [comment]
@yokawasa, pulled the latest code. Now it's working. Thanks for the help. One more thing, Custom log is now created in my log analytics workspace, but not able to see any data. How long does it take for the data to appear in azure?

**Comment by yokawasa** [comment]
@jahidakhtargit 
There are factors that affect the latency. From my experience, it's somewhere between 5min and 10min. It may be improved in the future but I don't know. The latency I mean here is the time it takes for log data to become available after it's collected. 

I'm closing this issue but please feel free to re-open if you have further discussion.

**Comment by jahidakhtargit** [comment]
@yokawasa, is there a way to delete the log created through code in azure?

**Comment by yokawasa** [comment]
@jahidakhtargit 
I haven't tried but it seems you can delete the log with Purge API. here are references:

- https://docs.microsoft.com/en-us/azure/azure-monitor/platform/personal-data-mgmt#delete
- https://docs.microsoft.com/en-us/rest/api/loganalytics/workspaces%202015-03-20/purge
