### ISSUE TITLE
Unable to set/use proxy

### ISSUE THREAD

**Issue by rogierg** [yokawasa/azure-log-analytics-data-collector#3]
Hi there,

The collector works great, at least on my computer it does. The problem is that our production environment requires me to use a proxy. I have not yet been able to get this working.

I've tried hacking it into net/http/persistent.rb (by setting proxy=:ENV) but this does not seem to work. I'm not even sure this is used by the collector.

Any information that would point me in the right direction is appreciated!

**Comment by yokawasa** [comment]
@rogierg 
Can you provide a bit more info on your issue?
You are seeing issues connecting to the data collector API (external service) through the proxy - Correct? Any error messages/error code?

**Comment by rogierg** [comment]
@yokawasa: the client does not use the proxy specified in any variable, and neither can I configure it in the output.

I was able to get this to work by modifying the datacollectorapi's client.rb:
```
          RestClient.proxy = ENV['http_proxy']
          res = RestClient.post( uri, body, headers)
          res
        end
```

**Comment by yokawasa** [comment]
@rogierg thank you so much!!
I added set_proxy method in client.rb at the package `azure-loganalytics-datacollector-api-0.1.4`. You can set proxy like this:
```ruby
client=Azure::Loganalytics::Datacollectorapi::Client::new( customer_id, shared_key)
client.set_proxy('YOUR PROXY') 
res = client.post_data(log_type, posting_records)
```
I'm closing this but please re-open if you need further discussion.
