### ISSUE TITLE
read log data from the Azure Log Analytics work space 

### ISSUE THREAD

**Issue by ponnagantichandu** [yokawasa/azure-log-analytics-data-collector#6]
I able to write the log data into the azure log analytics but in this Repo having the post method only since we don't have read method.

**Comment by yokawasa** [comment]
@ponnagantichandu Sorry for the delay. 
Unfortunately, azure-log-analytics-data-collector is a wrapper library for [Azure Log Analytics HTTP Data Collecotr API](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/data-collector-api) which doesn't provide log reading capabilities. So we won't support read in this as well
