### ISSUE TITLE
Support setting the x-ms-AzureResourceId	Header

### ISSUE THREAD

**Issue by floriankoch** [yokawasa/azure-log-analytics-data-collector#8]
This is needed to use Ressource Based Permissions.
Without this it is not possible to restict custom log access

If implemented, its also needed in https://github.com/yokawasa/fluent-plugin-azure-loganalytics

**Comment by yokawasa** [comment]
@floriankoch thank you so much for your bringing this out. 
Now both azure-log-analytics-data-collector and fluent-plugin-azure-loganalytcis support setting the x-ms-AzureResourceId Header. I go ahead to close the issue.

**Comment by floriankoch** [comment]
@yokawasa thank you  very much
